### ISSUE TITLE
Odkazy na Knihobot

### ISSUE THREAD

**Issue by nadhled** [petrboros/novysvet#1]
Dovolil jsem si to prolinkovat na Knihobot, nemusí to dávat největší smysl, ale chtěl jsem to zachovat jednotné. Část z nich vede na hlídacího psa, neb je ještě v historii neměli skladem.

- [Miroslav Bárta, Martin Kovář & Otakar Foltýn – Na rozhraní](https://knihobot.cz/g/215228)
- [Miroslav Bárta - Sedm zákonů: Jak civilizace vznikají, dosahují vrcholu a upadají](https://knihobot.cz/g/2996)
- [Jeremy Popkin – A New World Begins: The History of the French Revolution](https://knihobot.cz/hlidacipes?q=Jeremy%20Popkin%20A%20New%20World%20Begins)
- [Charles de Gaulle – Válečné paměti](https://knihobot.cz/g/248782)

- [Fareed Zakaria – Budoucnost svobody](https://knihobot.cz/g/125996)
- [Hillary Clinton – What happened](https://knihobot.cz/g/242948)

- [Henry Kissinger – Leadership](https://knihobot.cz/hlidacipes?q=Henry%20Kissinger%20Leadership)

- [Michel Houellebecq – Podvolení](https://knihobot.cz/g/72943)
- [Michel Houellebecq – Zničit](https://knihobot.cz/g/601950)
- [Michel Houellebecq – Serotonin](https://knihobot.cz/g/16610)

- [Ernest Hemingway – Smrt odpoledne - 1981](https://knihobot.cz/g/309967)
[Ernest Hemingway – Smrt odpoledne - 1982](https://knihobot.cz/g/441694)
- [Ernest Hemingway – Fiesta](https://knihobot.cz/p/q/Ernest%20Hemingway%20%E2%80%93%20Fiesta/language/1)
- [Phil Ball – Bílá bouře](https://knihobot.cz/g/168422)

- [Chris Miller – Chip War](https://knihobot.cz/hlidacipes?q=Chris%20Miller%20Chip%20War)

- [Christian Norbert-Schulz – Genius loci](https://knihobot.cz/p/q/christian%20Genius%20loci)
- [Gad Shimron – Mossad Exodus](https://knihobot.cz/hlidacipes?q=Gad%20Shimron%20Mossad%20Exodus)

- [Larry Collins, Dominique Lapierre – Ó Jeruzaléme](https://knihobot.cz/g/46357)
- [Larry Collins, Dominique Lapierre – O půlnoci přijde svoboda](https://knihobot.cz/g/365668)
- [Larry Collins, Dominique Lapierre – Hoří už Paříž?](https://knihobot.cz/p/q/Ho%C5%99%C3%AD%20u%C5%BE%20Pa%C5%99%C3%AD%C5%BE)
- [Agatha Christie – Schůzka se smrtí](https://knihobot.cz/p/q/Sch%C5%AFzka%20se%20smrt%C3%AD)
- [Jonathan Littell – Laskavé bohyně](https://knihobot.cz/p/q/Jonathan%20Littell%20%E2%80%93%20Laskav%C3%A9%20bohyn%C4%9B)
- [Hannah Arendt – Eichmann v Jeruzalémě: Zpráva o banalitě zla](https://knihobot.cz/g/23407)

- [Ondřej Houska – Praha proti Římu: Československo-italské vztahy v letech 1922–1929](https://knihobot.cz/g/110213)
- [Ian McEwan – Cizinci ve městě](https://knihobot.cz/g/98988)
- [Giuseppe Tomasi di Lampedusa – Gepard](https://knihobot.cz/p/q/Giuseppe%20Tomasi%20di%20Lampedusa%20%E2%80%93%20Gepard)

- [Lenka Hrabalová – Mozaikou Íránu](https://knihobot.cz/g/638891)
- [Elias Canetti – Masa a moc](https://knihobot.cz/g/17120)

- [John Glubb – Osudy říší: Jak zajistit naše přežití](https://knihobot.cz/hlidacipes?q=John%20Glubb%20Osudy%20%C5%99%C3%AD%C5%A1%C3%AD)
- [Jan Zábrana – Celý život](https://knihobot.cz/p/q/Jan%20Z%C3%A1brana%20%E2%80%93%20Cel%C3%BD%20%C5%BEivot)
- [Martin Amis – Peníze](https://knihobot.cz/g/138203)
- [Isaac Asimov – Nadace](https://knihobot.cz/p/q/Isaac%20Asimov%20%E2%80%93%20Nadace)
- [Robert Heinlein – Friday](https://knihobot.cz/g/154139)
- [Robert Heinlein – Měsíc je drsná milenka](https://knihobot.cz/p/q/Robert%20Heinlein%20%E2%80%93%20M%C4%9Bs%C3%ADc%20je%20drsn%C3%A1%20milenka)
- [Edward Gibbon – Úpadek a pád římské říše](https://knihobot.cz/p/q/Edward%20Gibbon%20%E2%80%93%20%C3%9Apadek%20a%20p%C3%A1d%20%C5%99%C3%ADmsk%C3%A9%20%C5%99%C3%AD%C5%A1e)
- [Alan Palmer – Úpadek a pád osmanské říše](https://knihobot.cz/g/113022)
- [Arnold Toynbee – Studium dějin](https://knihobot.cz/g/59162)
- [Joseph Tainter – Kolapsy složitých společností](https://knihobot.cz/p/q/Joseph%20Tainter%20%E2%80%93%20Kolapsy%20slo%C5%BEit%C3%BDch%20spole%C4%8Dnost%C3%AD)
- [Peter Turchin – Dynamics of political instability in the United States](https://knihobot.cz/hlidacipes?q=Peter%20Turchin%20Dynamics%20of%20political%20instability%20in%20the%20United%20States)
- [Mancur Olson – Vzestup a pád národů: ekonomický růst, stagflace a společenská rigidita](https://knihobot.cz/g/232045)
[Mancur Olson – Vzestup a pád národů: ekonomický růst, stagflace a společenská rigidita - ebook zdarma](https://libinst.cz/book/olson-m-1984-vzestup-a-pad-narodu/)
- [Robert Graves – Já, Claudius](https://knihobot.cz/p/q/Robert%20Graves%20%E2%80%93%20J%C3%A1%2C%20Claudius)

- [Frederick Forsyth – Den pro Šakala](https://knihobot.cz/p/q/Frederick%20Forsyth%20%E2%80%93%20Den%20pro%20%C5%A0akala)
- [Marcel Pagnol – Jak voní tymián](https://knihobot.cz/p/q/Marcel%20Pagnol%20%E2%80%93%20Jak%20von%C3%AD%20tymi%C3%A1n)
- [Alexandre Dumas – Hrabě Monte Cristo](https://knihobot.cz/p/q/Alexandre%20Dumas%20%E2%80%93%20Hrab%C4%9B%20Monte%20Cristo)
- [Marian Kechlibar – Krvavé levandule](https://knihobot.cz/g/23149)
- [Henri Barbusse – Oheň](https://knihobot.cz/p/q/Henri%20Barbusse%20%E2%80%93%20Ohe%C5%88)

**Comment by petrboros** [comment]
díky moc! doplním to s příštím updatem přímo do hlavní stránky

**Comment by petrboros** [comment]
doplněno, děkuji uctivě :)
